version: "3.9"

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  iam:
    build: ./services/iam
    env_file:
      - .env
      - ./services/iam/.env 
    ports:
      - "8001:8001"
    volumes:
      - ./services/iam/app:/app/app
    depends_on:
      - postgres

  patient-registry:
    build: ./services/patient-registry
    env_file:
      - ./services/patient-registry/.env
    ports:
      - "8002:8002"
    depends_on:
      - postgres

  emergency-health:
    build: ./services/emergency-health
    env_file:
      - ./services/emergency-health/.env
    ports:
      - "8003:8003"
    depends_on:
      - postgres

  biometric:
    build: ./services/biometric
    env_file:
      - ./services/biometric/.env
    ports:
      - "8004:8004"

  audit:
    build: ./services/audit
    env_file:
      - ./services/audit/.env
    ports:
      - "8005:8005"
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    build: ./services/gateway
    env_file:
      - ./services/gateway/.env
    ports:
      - "8000:8000"
    depends_on:
      - iam
      - patient-registry
      - emergency-health
      - biometric
      - audit
